// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3WJi9Zhpb1ZnEfUsc8RNQ2GZ-qmThJXg',
    appId: '1:477695698839:web:96604fe6c5c467364e46d2',
    messagingSenderId: '477695698839',
    projectId: 'find-my-phone-74741',
    authDomain: 'find-my-phone-74741.firebaseapp.com',
    storageBucket: 'find-my-phone-74741.firebasestorage.app',
    measurementId: 'G-QC5TWNQH90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBauOAptHvlZfgZ2J7VKQI40tM_s2HJ_uM',
    appId: '1:477695698839:android:15b747a74cfb30a64e46d2',
    messagingSenderId: '477695698839',
    projectId: 'find-my-phone-74741',
    storageBucket: 'find-my-phone-74741.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6pW8WscBj8xhVknNIE3pPwXCMfx8tnns',
    appId: '1:477695698839:ios:6e2b90c1cd1272194e46d2',
    messagingSenderId: '477695698839',
    projectId: 'find-my-phone-74741',
    storageBucket: 'find-my-phone-74741.firebasestorage.app',
    iosBundleId: 'com.example.secureFindMyPhone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6pW8WscBj8xhVknNIE3pPwXCMfx8tnns',
    appId: '1:477695698839:ios:6e2b90c1cd1272194e46d2',
    messagingSenderId: '477695698839',
    projectId: 'find-my-phone-74741',
    storageBucket: 'find-my-phone-74741.firebasestorage.app',
    iosBundleId: 'com.example.secureFindMyPhone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3WJi9Zhpb1ZnEfUsc8RNQ2GZ-qmThJXg',
    appId: '1:477695698839:web:44f35b9b404f424b4e46d2',
    messagingSenderId: '477695698839',
    projectId: 'find-my-phone-74741',
    authDomain: 'find-my-phone-74741.firebaseapp.com',
    storageBucket: 'find-my-phone-74741.firebasestorage.app',
    measurementId: 'G-C9SRW59GFV',
  );
}
