import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:http/http.dart' as http;
import 'package:location/location.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

const String API_BASE = "http://192.168.2.133:8000"; // Change to your server

Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  print('Background message received: ${message.data}');
  await handlePing(message.data);
}

Future<void> handlePing(Map<String, dynamic> data) async {
  if (data['command'] == 'locate') {
    final loc = Location();
    bool serviceEnabled = await loc.serviceEnabled();
    if (!serviceEnabled) {
      serviceEnabled = await loc.requestService();
      if (!serviceEnabled) return;
    }

    PermissionStatus permissionGranted = await loc.hasPermission();
    if (permissionGranted == PermissionStatus.denied) {
      permissionGranted = await loc.requestPermission();
      if (permissionGranted != PermissionStatus.granted) return;
    }

    LocationData locationData = await loc.getLocation();

    final prefs = await SharedPreferences.getInstance();
    final user = prefs.getString('username') ?? 'unknown_device';

    final body = jsonEncode({
      "user": user,
      "latitude": locationData.latitude,
      "longitude": locationData.longitude,
      "timestamp": DateTime.now().millisecondsSinceEpoch ~/ 1000
    });

    await http.post(
      Uri.parse("$API_BASE/location"),
      headers: {"Content-Type": "application/json"},
      body: body,
    );
  }
}

Future<void> registerDevice(String user, String fcmToken) async {
  final body = jsonEncode({"user": user, "token": fcmToken});
  await http.post(
    Uri.parse("$API_BASE/register"),
    headers: {"Content-Type": "application/json"},
    body: body,
  );
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Find My Phone',
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatefulWidget {
  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  String? _fcmToken;
  String _status = "Initializing...";

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      initFCM();
    });
  }

  Future<void> promptUsername() async {
    final prefs = await SharedPreferences.getInstance();
    String? username = prefs.getString('username');

    if (username != null) return;

    final controller = TextEditingController();
    username = await showDialog<String>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Enter device name'),
        content: TextField(
          controller: controller,
          decoration: const InputDecoration(
            hintText: 'Alice\'s Phone',
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, controller.text.trim()),
            child: const Text('OK'),
          ),
        ],
      ),
    );

    if (username != null && username.isNotEmpty) {
      await prefs.setString('username', username);
    }
  }

  void initFCM() async {
    try {
      await promptUsername();

      final prefs = await SharedPreferences.getInstance();
      final username = prefs.getString('username') ?? 'unknown_device';

      setState(() => _status = "Initializing Firebase...");

      FirebaseMessaging messaging = FirebaseMessaging.instance;

      String? token = await messaging.getToken();
      if (token == null) {
        setState(() => _status = "Failed to get FCM token");
        return;
      }

      _fcmToken = token;
      setState(() => _status = "Token acquired");

      await registerDevice(username, token);
      setState(() => _status = "Registered as $username");

      FirebaseMessaging.onMessage.listen((RemoteMessage message) async {
        setState(() => _status += "\nMessage: ${message.data}");
        await handlePing(message.data);
      });
    } catch (e) {
      setState(() => _status = "Error: $e");
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Find My Phone')),
      body: Padding(
        padding: EdgeInsets.all(16),
        child: SingleChildScrollView(
          child: Text(_status),
        ),
      ),
    );
  }
}
