import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:http/http.dart' as http;
import 'package:location/location.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

const String API_BASE = "http://192.168.2.133:8000"; // Change to your server

Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  print('Background message received: ${message.data}');
  await handlePing(message.data);
}

Future<void> handlePing(Map<String, dynamic> data) async {
  // Only handle 'locate' command for now
  if (data['command'] == 'locate') {
    final loc = Location();
    bool serviceEnabled = await loc.serviceEnabled();
    if (!serviceEnabled) {
      serviceEnabled = await loc.requestService();
      if (!serviceEnabled) return;
    }

    PermissionStatus permissionGranted = await loc.hasPermission();
    if (permissionGranted == PermissionStatus.denied) {
      permissionGranted = await loc.requestPermission();
      if (permissionGranted != PermissionStatus.granted) return;
    }

    LocationData locationData = await loc.getLocation();

    // Send location to backend
    final body = jsonEncode({
      "user": "alice", // hardcoded or use saved username
      "latitude": locationData.latitude,
      "longitude": locationData.longitude,
      "timestamp": DateTime.now().millisecondsSinceEpoch ~/ 1000
    });

    await http.post(
      Uri.parse("$API_BASE/location"),
      headers: {"Content-Type": "application/json"},
      body: body,
    );
  }
}

Future<void> registerDevice(String user, String fcmToken) async {
  final body = jsonEncode({"user": user, "token": fcmToken});
  await http.post(
    Uri.parse("$API_BASE/register"),
    headers: {"Content-Type": "application/json"},
    body: body,
  );
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String? _fcmToken;
  String _status = "Initializing...";

  @override
  void initState() {
    super.initState();
    initFCM();
  }

  void initFCM() async {
    FirebaseMessaging messaging = FirebaseMessaging.instance;

    // Get token
    String? token = await messaging.getToken();
    if (token != null) {
      _fcmToken = token;
      setState(() => _status = "Token acquired: $token");
      // Register device with backend
      await registerDevice("alice", token);
      setState(() => _status += "\nRegistered with backend.");
    }

    // Foreground message handler
    FirebaseMessaging.onMessage.listen((RemoteMessage message) async {
      setState(
          () => _status += "\nForeground message received: ${message.data}");
      await handlePing(message.data);
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Find My Phone',
      home: Scaffold(
        appBar: AppBar(title: Text('Find My Phone')),
        body: Padding(
          padding: EdgeInsets.all(16),
          child: SingleChildScrollView(
            child: Text(_status),
          ),
        ),
      ),
    );
  }
}
